// Bundles the knowledge base (docs/**/*.{md,mdx}) into a single stable string
// that the Cloudflare Pages Function imports. Run before `build` and `start`
// via the prebuild/prestart npm scripts.
//
// Stable byte output matters: the bundled string becomes the cached prefix of
// Claude's system prompt, so deterministic ordering keeps prompt caching warm.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative, sep, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS_DIR = join(ROOT, 'docs');
const OUT_FILE = join(ROOT, 'functions', 'api', 'kb-content.ts');

/** Recursively collect .md/.mdx files under docs/, returned as repo-relative paths. */
function collectDocs(dir) {
  const entries = readdirSync(dir, { withFileTypes: true, recursive: true });
  return entries
    .filter((e) => e.isFile() && /\.mdx?$/.test(e.name))
    // e.parentPath is available on Node >=20.12; fall back to e.path for older 20.x
    .map((e) => join(e.parentPath ?? e.path, e.name))
    .map((abs) => relative(ROOT, abs).split(sep).join('/'))
    .sort();
}

const files = collectDocs(DOCS_DIR);

const blocks = files.map((relPath) => {
  const text = readFileSync(join(ROOT, relPath), 'utf8').trim();
  return `===== FILE: ${relPath} =====\n${text}`;
});

const kb = blocks.join('\n\n');

const banner = '// AUTO-GENERATED by scripts/build-kb.mjs — do not edit by hand.\n';
const out =
  banner +
  `export const KB = ${JSON.stringify(kb)};\n` +
  // Debugging metadata only — keep out of the cached system prefix.
  `export const KB_FILE_COUNT = ${files.length};\n`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out, 'utf8');

console.log(
  `[build-kb] bundled ${files.length} docs (${kb.length} chars) -> ${relative(ROOT, OUT_FILE)}`
);
